#!/usr/bin/env sh
# this script will set appropriate environment variables
# so that we can add flexibility and robustness to our work
# environment.

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
  fi

#set our editor to something nice :)
export EDITOR=vim


# we will set the current directory as our home directory so
# scripts can run from anywhere correctly.  All scripts
# must reference WEBSERVER_DEVEL_HOME and this script
# to document what is happening.
# Absolute path to this script, which happens to reside in the
# top-level of the webserver application - therefore providing us
# the location for home.
export WEBSERVER_DEVEL_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# the source directory, where our source files are located
export WEBSERVER_DEVEL_SOURCE="$WEBSERVER_DEVEL_HOME/source"

# the build directory, where compiled files are located
export WEBSERVER_DEVEL_BUILD="$WEBSERVER_DEVEL_HOME/build"

# we will add the script directory to our path so we can run
# the build scripts from anywhere.
export WEBSERVER_DEVEL_SCRIPT="$WEBSERVER_DEVEL_HOME/scripts"

export PATH=$PATH:$WEBSERVER_DEVEL_SCRIPT

# Setting an environment variable to indicate this file
# was run.
export WEBSERVER_ENV_VARIABLES="configured"


echo
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "invoking subshell.  Note you are now in a subshell"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
#change the prompt so it's clear we are in dev mode.
export PS1="[Developing] [\W] \$ "

devhelp() {
  echo "            --- HELP ---         "
  echo "  The following scripts can be used anywhere: "
  echo "   build_server.sh - builds objects that need compilation and"
  echo "                     links them together as needed for non-test usage"
  echo
  echo "   delete_all_compiled.sh - simply deletes the build directory"
  echo
  echo "   delete_objects.sh - deletes all the object files in build directory"
  echo
  echo "   delete_server.sh - deletes the server executable"
  echo
  echo "   delete_tests.sh - deletes the test executables"
  echo
  echo "   run_and_delete_tests.sh - runs the tests, then deletes the test executables"
 
}



# vim: ai:tw=70
