#!/usr/bin/env bash
# this script will set appropriate environment variables
# so that we can add flexibility and robustness to our work
# environment.

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
  fi

#set our editor to something nice :)
export EDITOR=vim


# we will set the current directory as our home directory so
# scripts can run from anywhere correctly.  All scripts
# must reference WEBSERVER_DEVEL_HOME and this script
# to document what is happening.
# Absolute path to this script, which happens to reside in the
# top-level of the webserver application - therefore providing us
# the location for home.
export WEBSERVER_DEVEL_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# the source directory, where our source files are located
export WEBSERVER_DEVEL_SOURCE="$WEBSERVER_DEVEL_HOME/source"

# the top-level build directory, where compiled files are located
export WEBSERVER_DEVEL_BUILD="$WEBSERVER_DEVEL_HOME/build"

# the object build directory, where objects are located
export WEBSERVER_DEVEL_OBJECTS="$WEBSERVER_DEVEL_BUILD/objects"

# the test build directory, where test executables are located
export WEBSERVER_DEVEL_TESTS="$WEBSERVER_DEVEL_BUILD/tests"

# the non-test build directory, where non-test executables are stored
export WEBSERVER_DEVEL_EXEC="$WEBSERVER_DEVEL_BUILD/exec"

# we will add the script directory to our path so we can run
# the build scripts from anywhere.
export WEBSERVER_DEVEL_SCRIPT="$WEBSERVER_DEVEL_HOME/scripts"

export PATH=$PATH:$WEBSERVER_DEVEL_SCRIPT

# Setting an environment variable to indicate this file
# was run.
export WEBSERVER_ENV_VARIABLES="configured"

# choose the c compiler we want to use.
export WEBSERVER_C_COMPILER="gcc"

devhelp() {
  echo "            --- HELP ---         "
  echo "      (run devhelp to see this again)"
  echo
  echo "  The following scripts can be used anywhere: "
  echo "   build_program.sh - builds objects that need compilation and"
  echo "                     links them together as needed for non-test usage"
  echo
  echo "   delete_build.sh - simply deletes the build directory"
  echo "   run_tests.sh - builds, links, and runs the tests"
  echo "   run_program.sh - builds, links, then runs program"
  echo
 
}

echo
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "invoking subshell.  Note you are now in a subshell"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
devhelp
#change the prompt so it's clear we are in dev mode.
export PS1="[Developing] [\W] \$ "




# vim: ai:tw=70
